/**
 * Stargazer — moon-side constellation game
 *
 * Mechanic:
 *   - A constellation template is drawn at random. Length is usually 3..7
 *     ("common"); 8..9 are rare "Great Constellations" (~10%).
 *   - A digit sequence is generated by Fisher-Yates shuffle from 1..9 without
 *     replacement, truncated to constellation length. The HUD shows the
 *     current expected digit; previewed digits sit beneath the card.
 *   - Correct press: a star lifts out of the jar, arcs into the sky, locks
 *     onto the next predetermined point in the pattern.
 *   - `0` is the universal release key — once all stars are placed, pressing
 *     `0` connects them with luminous lines, names the constellation, and
 *     drifts it to the persistent sky map.
 *   - Wrong digit: a tiny shooting star streaks across the horizon. No
 *     progress, no punishment.
 *
 * Persistence (via Utils.Storage):
 *   - winnieos.stargazer.totalStars   (number)
 *   - winnieos.stargazer.collected    (array of { name, length, stars[{xN,yN}], edges, ts })
 *
 * Factory returns { start, dispose, api } following the WinnieOS game contract.
 */

import { Audio } from '../../utils/audio.js';
import { Storage } from '../../utils/storage.js';
import { Background } from '../../utils/background.js';
import { CONSTELLATIONS } from './constellations.js';

const STORAGE_KEY_STARS = 'stargazer.totalStars';
const STORAGE_KEY_COLLECTED = 'stargazer.collected';

// Sky region (where stars get placed) — fraction of canvas height.
// Top is positioned below the HUD card so the constellation never hides
// behind the digit display. Bottom sits just above the moon's horizon.
const SKY_TOP = 0.24;
const SKY_BOTTOM = 0.56;

// Length distribution per constellation:
//   3..7 are common, 8..9 are rare ("Great Constellations") at ~1-in-10.
function pickConstellationTemplate() {
    const greatRoll = Math.random() < 0.10;
    const bucket = greatRoll
        ? CONSTELLATIONS.filter(c => c.length >= 8)
        : CONSTELLATIONS.filter(c => c.length >= 3 && c.length <= 7);
    const pool = bucket.length > 0 ? bucket : CONSTELLATIONS;
    return pool[(Math.random() * pool.length) | 0];
}

function nowMs() {
    return (typeof performance !== 'undefined' && performance.now)
        ? performance.now()
        : Date.now();
}

function clamp(n, lo, hi) {
    return Math.max(lo, Math.min(hi, n));
}

function ease(t) {
    // easeInOutCubic
    return t < 0.5 ? 4 * t * t * t : 1 - Math.pow(-2 * t + 2, 3) / 2;
}

function easeOutBack(t) {
    const c1 = 1.70158;
    const c3 = c1 + 1;
    return 1 + c3 * Math.pow(t - 1, 3) + c1 * Math.pow(t - 1, 2);
}

// Path2D-less rounded rect — kept here so any draw routine can use it.
function roundRect(c, x, y, w, h, r) {
    const rr = Math.min(r, w / 2, h / 2);
    c.beginPath();
    c.moveTo(x + rr, y);
    c.lineTo(x + w - rr, y);
    c.quadraticCurveTo(x + w, y, x + w, y + rr);
    c.lineTo(x + w, y + h - rr);
    c.quadraticCurveTo(x + w, y + h, x + w - rr, y + h);
    c.lineTo(x + rr, y + h);
    c.quadraticCurveTo(x, y + h, x, y + h - rr);
    c.lineTo(x, y + rr);
    c.quadraticCurveTo(x, y, x + rr, y);
    c.closePath();
}

// ── HSL helpers (for deriving sky palette from the desktop primary color) ──
function rgbToHsl(r, g, b) {
    r /= 255; g /= 255; b /= 255;
    const max = Math.max(r, g, b);
    const min = Math.min(r, g, b);
    const delta = max - min;
    let h = 0;
    if (delta !== 0) {
        if (max === r)      h = ((g - b) / delta) % 6;
        else if (max === g) h = (b - r) / delta + 2;
        else                h = (r - g) / delta + 4;
    }
    h = h * 60;
    if (h < 0) h += 360;
    const l = (max + min) / 2;
    const s = delta === 0 ? 0 : delta / (1 - Math.abs(2 * l - 1));
    return { h, s, l };
}

function hslToRgb(h, s, l) {
    h = ((h % 360) + 360) % 360;
    s = Math.max(0, Math.min(1, s));
    l = Math.max(0, Math.min(1, l));
    const c = (1 - Math.abs(2 * l - 1)) * s;
    const x = c * (1 - Math.abs((h / 60) % 2 - 1));
    const m = l - c / 2;
    let r = 0, g = 0, b = 0;
    if      (h < 60)  { r = c; g = x; b = 0; }
    else if (h < 120) { r = x; g = c; b = 0; }
    else if (h < 180) { r = 0; g = c; b = x; }
    else if (h < 240) { r = 0; g = x; b = c; }
    else if (h < 300) { r = x; g = 0; b = c; }
    else              { r = c; g = 0; b = x; }
    return {
        r: Math.round((r + m) * 255),
        g: Math.round((g + m) * 255),
        b: Math.round((b + m) * 255),
    };
}

function hslToCss(h, s, l) {
    const { r, g, b } = hslToRgb(h, s, l);
    return `rgb(${r},${g},${b})`;
}

// Rotate hue toward warm (h ≈ 0°) by `amount` (0..1) of the shortest arc.
// Lets us derive a "twilight" horizon from any primary color — green primaries
// drift toward amber, blues drift toward magenta, pinks deepen toward red.
function rotateTowardWarm(h, amount) {
    let diff = -h; // shortest signed arc to 0
    if (diff > 180) diff -= 360;
    if (diff < -180) diff += 360;
    return ((h + diff * amount) + 360) % 360;
}

function deriveSkyPalette(primaryHex) {
    const rgb = Background.hexToRgb(primaryHex);
    const hsl = rgbToHsl(rgb.r, rgb.g, rgb.b);
    const h = hsl.h;
    // Floor + ceiling on saturation so very-pale or very-grey primaries still
    // produce a sky with some color life.
    const s = Math.max(0.50, Math.min(0.90, hsl.s));
    return {
        top:     hslToCss(h,                                s * 0.60, 0.06),
        upper:   hslToCss(h,                                s * 0.62, 0.12),
        mid:     hslToCss(rotateTowardWarm(h, 0.30),        s * 0.55, 0.17),
        lower:   hslToCss(rotateTowardWarm(h, 0.60),        s * 0.48, 0.22),
        horizon: hslToCss(rotateTowardWarm(h, 0.85),        s * 0.42, 0.26),
    };
}

/**
 * @param {{
 *   canvas: HTMLCanvasElement,
 *   onStatsChange?: (totalStars: number, totalCons: number) => void,
 *   onConstellationNamed?: (name: string) => void,
 * }} opts
 */
export function createStargazerGame({ canvas, onStatsChange, onConstellationNamed }) {
    const ctx = canvas.getContext('2d');
    let disposed = false;

    // ── Dimensions ────────────────────────────────────────────────────────
    let W = canvas.width;
    let H = canvas.height;

    function syncSize() {
        W = canvas.width;
        H = canvas.height;
    }

    // ── Theme — derived from the desktop primary so the sky belongs to the
    // rest of the OS visually. Sampled once at start (the desktop color is
    // unlikely to change while she's playing).
    const primaryHex = Background.getSaved() || '#667eea';
    const skyPalette = deriveSkyPalette(primaryHex);

    // ── Persistent state ──────────────────────────────────────────────────
    let totalStars = Number(Storage.get(STORAGE_KEY_STARS, 0)) || 0;
    const storedCollected = Storage.get(STORAGE_KEY_COLLECTED, []);
    let collected = Array.isArray(storedCollected) ? storedCollected : [];

    function saveStars() { Storage.set(STORAGE_KEY_STARS, totalStars); }
    function saveCollected() { Storage.set(STORAGE_KEY_COLLECTED, collected); }

    function notifyStats() {
        if (onStatsChange) onStatsChange(totalStars, collected.length);
    }

    // ── Pre-baked starfield (the deep background — separate from collected) ──
    const BG_STAR_COUNT = 120;
    const bgStars = [];
    for (let i = 0; i < BG_STAR_COUNT; i++) {
        bgStars.push({
            xN: Math.random(),
            yN: Math.random() * 0.55, // only in sky region
            size: 0.4 + Math.random() * 1.0,
            twinkle: Math.random() * Math.PI * 2,
        });
    }

    // ── Moon surface craters (baked once so they don't dance every frame) ──
    const craters = [];
    {
        const cnt = 7;
        for (let i = 0; i < cnt; i++) {
            craters.push({
                xN: 0.05 + Math.random() * 0.9,
                yN: 0.62 + Math.random() * 0.32,
                rN: 0.018 + Math.random() * 0.045,
                tilt: (Math.random() - 0.5) * 0.5,
                squash: 0.5 + Math.random() * 0.3,
            });
        }
    }

    // ── Rolling-hill profile of the moon's surface (baked once) ──
    // Stored as normalized control points (x in 0..1, y in 0..1 of canvas).
    const hillProfile = [];
    {
        const steps = 8;
        let y = 0.62 + Math.random() * 0.03;
        for (let i = 0; i <= steps; i++) {
            const x = i / steps;
            y += (Math.random() - 0.5) * 0.04;
            y = clamp(y, 0.56, 0.66);
            hillProfile.push({ x, y });
        }
    }

    // ── Phases ────────────────────────────────────────────────────────────
    /** @type {'idle' | 'placing' | 'revealing' | 'completing'} */
    let phase = 'idle';

    /** @type {{ template: typeof CONSTELLATIONS[number], placedCount: number, digitSequence: number[], scale: number, xShift: number, flip: number } | null} */
    let current = null;

    // In-flight star animations (jar → target position).
    /** @type {Array<{ from: {x:number,y:number}, to: {x:number,y:number}, t0: number, dur: number, indexInConstellation: number }>} */
    const inFlight = [];

    // Stars currently placed in the constellation in progress.
    /** @type {Array<{ x: number, y: number, bornAt: number, indexInConstellation: number }>} */
    const placedStars = [];

    // Wrong-key shooting stars (decorative).
    /** @type {Array<{ x: number, y: number, vx: number, vy: number, age: number, maxAge: number, len: number }>} */
    const shootingStars = [];

    // Sparkle bursts (from star placement / reveal).
    /** @type {Array<{ x: number, y: number, dx: number, dy: number, r: number, life: number, color: string }>} */
    const particles = [];

    // Reveal animation state — set when 0 is pressed.
    /** @type {{ t0: number, dur: number } | null} */
    let reveal = null;

    // ── Helpers ───────────────────────────────────────────────────────────
    function skyToCanvas(xN, yN) {
        // Maps a normalized (0..1, 0..1) star position from the constellation
        // template into actual canvas coordinates within the sky region.
        // Honors `current`'s flip + scale + xShift for procedural variation.
        if (!current) {
            return { x: xN * W, y: (SKY_TOP + yN * (SKY_BOTTOM - SKY_TOP)) * H };
        }
        const cx = 0.5;
        let lx = (xN - cx) * current.scale * current.flip + cx + current.xShift;
        lx = clamp(lx, 0.08, 0.92);
        const sx = lx * W;
        const sy = (SKY_TOP + yN * (SKY_BOTTOM - SKY_TOP)) * H;
        return { x: sx, y: sy };
    }

    function jarPosition() {
        // Jar sits on the moon, slightly left-of-center, on a small mound.
        return { x: W * 0.34, y: H * 0.74 };
    }

    function jarMouthPosition() {
        const j = jarPosition();
        return { x: j.x, y: j.y - H * 0.04 };
    }

    function startNextConstellation() {
        const template = pickConstellationTemplate();
        // Random digit sequence drawn from 1..9 without replacement, then
        // truncated to constellation length. Each constellation exercises a
        // unique mix of digits (no within-constellation repeats), giving Winnie
        // the broadest digit exposure per session without the boredom of a
        // fixed countdown. 0 stays the universal release key.
        const pool = [1, 2, 3, 4, 5, 6, 7, 8, 9];
        // Fisher-Yates shuffle.
        for (let i = pool.length - 1; i > 0; i--) {
            const j = Math.floor(Math.random() * (i + 1));
            [pool[i], pool[j]] = [pool[j], pool[i]];
        }
        const digitSequence = pool.slice(0, template.length);
        current = {
            template,
            placedCount: 0,
            digitSequence,
            // Procedural variety so the same template looks different night-to-night.
            scale: 0.85 + Math.random() * 0.30,
            xShift: (Math.random() - 0.5) * 0.10,
            flip: Math.random() < 0.5 ? -1 : 1,
        };
        placedStars.length = 0;
        reveal = null;
        phase = 'placing';
    }

    function expectedDigit() {
        if (!current) return null;
        if (current.placedCount < current.digitSequence.length) {
            return current.digitSequence[current.placedCount];
        }
        return 0; // all stars placed → 0 is the release key
    }

    // ── Input (called from app.js via api.pressDigit) ─────────────────────
    function pressDigit(d) {
        if (disposed) return;
        if (phase === 'idle') startNextConstellation();
        // Only accept input during the placing phase. Once the climax `0` is
        // pressed the reveal animation runs uninterrupted — extra presses
        // during reveal/completing are ignored.
        if (phase !== 'placing' || !current) return;

        const expected = expectedDigit();
        if (d === expected) {
            if (d === 0) {
                triggerReveal();
            } else {
                placeNextStar();
            }
        } else {
            // Wrong key — gentle shooting star.
            spawnShootingStar();
            try { Audio.shootingStar(0.35); } catch (_) {}
        }
    }

    function placeNextStar() {
        const idx = current.placedCount;
        const tStar = current.template.stars[idx];
        if (!tStar) return;
        const dest = skyToCanvas(tStar.xN, tStar.yN);
        const from = jarMouthPosition();

        inFlight.push({
            from,
            to: dest,
            t0: nowMs(),
            dur: 720 + Math.random() * 90,
            indexInConstellation: idx,
        });

        // Pluck-from-jar audio cue.
        try { Audio.jarLift(0.5); } catch (_) {}

        current.placedCount++;
        // expectedDigit() now derives the next prompt from digitSequence (or
        // returns 0 once all stars are placed).

        totalStars++;
        saveStars();
        notifyStats();
    }

    function triggerReveal() {
        if (!current) return;
        phase = 'revealing';
        reveal = {
            t0: nowMs(),
            dur: 2200,
        };
        try { Audio.constellationReveal(0.8); } catch (_) {}
        if (onConstellationNamed && current.template) {
            // Tell the DOM banner ~halfway through the reveal so the name
            // arrives just as the lines complete their draw.
            setTimeoutSafe(() => {
                if (current && current.template) {
                    onConstellationNamed(current.template.name);
                }
            }, 900);
        }
    }

    function completeConstellation() {
        if (!current) return;
        // Snapshot the actual positions used (with this run's scale/flip/shift)
        // so the persistent sky map shows the constellation exactly where she
        // saw it form.
        const placedSnap = placedStars.map(s => ({ xN: s.x / W, yN: s.y / H }));
        collected.push({
            name: current.template.name,
            length: current.template.length,
            edges: current.template.edges,
            stars: placedSnap,
            ts: Date.now(),
        });
        saveCollected();
        notifyStats();
        current = null;
        placedStars.length = 0;
        reveal = null;
        phase = 'idle';

        // Brief breath, then the next constellation.
        setTimeoutSafe(() => {
            if (!disposed) startNextConstellation();
        }, 1500);
    }

    function spawnShootingStar() {
        // Streak across the upper sky, left-to-right or right-to-left at random.
        const ltr = Math.random() < 0.5;
        const y0 = (SKY_TOP + Math.random() * (SKY_BOTTOM - SKY_TOP) * 0.5) * H;
        const speed = 14 + Math.random() * 6;
        const angle = (ltr ? 1 : -1) * (0.08 + Math.random() * 0.08); // mostly horizontal
        const vx = (ltr ? 1 : -1) * speed * Math.cos(angle);
        const vy = speed * Math.sin(angle);
        const x0 = ltr ? -40 : W + 40;
        shootingStars.push({
            x: x0, y: y0, vx, vy, age: 0, maxAge: 60, len: 80,
        });
    }

    function spawnSparkleBurst(x, y, count, palette) {
        for (let i = 0; i < count; i++) {
            const a = Math.random() * Math.PI * 2;
            const s = 0.5 + Math.random() * 2.5;
            particles.push({
                x, y,
                dx: Math.cos(a) * s, dy: Math.sin(a) * s - 0.6,
                r: 0.8 + Math.random() * 1.6,
                life: 28 + (Math.random() * 18) | 0,
                color: palette[(Math.random() * palette.length) | 0],
            });
        }
    }

    const STAR_SPARKLE_COLORS = ['#fffbea', '#ffe9a8', '#cde0ff', '#ffffff'];
    const REVEAL_SPARKLE_COLORS = ['#fffbea', '#ffe07a', '#ffd166', '#fff5d0'];

    // ── Timers tracked for clean disposal ─────────────────────────────────
    const timers = new Set();
    function setTimeoutSafe(fn, ms) {
        const id = setTimeout(() => {
            timers.delete(id);
            if (!disposed) fn();
        }, ms);
        timers.add(id);
        return id;
    }

    // ── Rendering ─────────────────────────────────────────────────────────
    function drawSky() {
        // Vertical gradient derived from the desktop primary color. Mapped
        // 0..horizonY but we fill the ENTIRE canvas — any pixel below the last
        // stop solidifies in the horizon color, so there's never a gap between
        // the sky and the moon's curved top edge. Moon overdraws the bottom.
        const horizonY = (hillProfile[0]?.y || 0.62) * H;
        const g = ctx.createLinearGradient(0, 0, 0, horizonY);
        g.addColorStop(0,    skyPalette.top);
        g.addColorStop(0.45, skyPalette.upper);
        g.addColorStop(0.78, skyPalette.mid);
        g.addColorStop(0.92, skyPalette.lower);
        g.addColorStop(1,    skyPalette.horizon);
        ctx.fillStyle = g;
        ctx.fillRect(0, 0, W, H);
    }

    function drawBackgroundStars(now) {
        ctx.save();
        for (let i = 0; i < bgStars.length; i++) {
            const s = bgStars[i];
            const tw = 0.55 + 0.45 * Math.sin(now * 0.0008 + s.twinkle);
            const x = s.xN * W;
            const y = s.yN * H;
            ctx.fillStyle = `rgba(255,250,230,${0.30 + 0.35 * tw})`;
            ctx.beginPath();
            ctx.arc(x, y, s.size, 0, Math.PI * 2);
            ctx.fill();
        }
        ctx.restore();
    }

    function drawCollectedConstellations(now) {
        if (collected.length === 0) return;
        // The lines from prior nights only mattered in the moment of reveal —
        // persisting them piles up as visual noise. What persists instead are
        // the *stars themselves*: Winnie's sky genuinely fills with more stars
        // over sessions, but they read as background starfield, not as
        // overlaid shapes competing with tonight's constellation.
        ctx.save();
        for (let i = 0; i < collected.length; i++) {
            const c = collected[i];
            for (let s = 0; s < c.stars.length; s++) {
                const st = c.stars[s];
                const tw = 0.55 + 0.45 * Math.sin(now * 0.0008 + i * 0.7 + s * 0.5);
                const x = st.xN * W;
                const y = st.yN * H;
                ctx.fillStyle = `rgba(255,250,230,${0.42 + 0.30 * tw})`;
                ctx.beginPath();
                ctx.arc(x, y, 1.0, 0, Math.PI * 2);
                ctx.fill();
            }
        }
        ctx.restore();
    }

    function drawEarth(now) {
        const ex = W * 0.76;
        const ey = H * 0.20;
        const er = Math.min(W, H) * 0.068;

        ctx.save();
        // Soft halo
        const halo = ctx.createRadialGradient(ex, ey, er * 0.6, ex, ey, er * 2.6);
        halo.addColorStop(0,    'rgba(120,180,240,0.22)');
        halo.addColorStop(0.5,  'rgba(120,180,240,0.08)');
        halo.addColorStop(1,    'rgba(120,180,240,0)');
        ctx.fillStyle = halo;
        ctx.beginPath();
        ctx.arc(ex, ey, er * 2.6, 0, Math.PI * 2);
        ctx.fill();

        // Earth body — gradient blue-green
        const body = ctx.createRadialGradient(ex - er * 0.35, ey - er * 0.35, er * 0.2, ex, ey, er);
        body.addColorStop(0,   '#a8d4f0');
        body.addColorStop(0.5, '#5d9fd4');
        body.addColorStop(1,   '#1d4a78');
        ctx.fillStyle = body;
        ctx.beginPath();
        ctx.arc(ex, ey, er, 0, Math.PI * 2);
        ctx.fill();

        // Subtle landmass swirls — quick painterly suggestion. Clipped to the
        // Earth disc so the strokes never leak past the sphere edge.
        ctx.save();
        ctx.beginPath();
        ctx.arc(ex, ey, er, 0, Math.PI * 2);
        ctx.clip();
        ctx.fillStyle = 'rgba(120,180,90,0.32)';
        ctx.beginPath();
        ctx.ellipse(ex - er * 0.2, ey + er * 0.15, er * 0.45, er * 0.18, 0.4, 0, Math.PI * 2);
        ctx.fill();
        ctx.beginPath();
        ctx.ellipse(ex + er * 0.25, ey - er * 0.15, er * 0.3, er * 0.12, -0.3, 0, Math.PI * 2);
        ctx.fill();
        ctx.restore();

        ctx.restore();
    }

    function drawMoonSurface() {
        ctx.save();

        // Soft glow above the horizon line (moonlight bouncing up from the surface)
        const horizonY = (hillProfile[0]?.y || 0.62) * H;
        const glow = ctx.createLinearGradient(0, horizonY - 60, 0, horizonY + 20);
        glow.addColorStop(0, 'rgba(255,240,210,0)');
        glow.addColorStop(1, 'rgba(255,240,210,0.18)');
        ctx.fillStyle = glow;
        ctx.fillRect(0, horizonY - 60, W, 80);

        // Lunar fill — gradient from a warm cream at the horizon to cool grey at the bottom
        ctx.beginPath();
        ctx.moveTo(0, H);
        ctx.lineTo(0, hillProfile[0].y * H);
        for (let i = 1; i < hillProfile.length; i++) {
            // Cubic-ish smoothness via quadraticCurveTo midpoints
            const prev = hillProfile[i - 1];
            const cur = hillProfile[i];
            const midX = (prev.x + cur.x) / 2 * W;
            const midY = (prev.y + cur.y) / 2 * H;
            ctx.quadraticCurveTo(prev.x * W, prev.y * H, midX, midY);
        }
        const last = hillProfile[hillProfile.length - 1];
        ctx.lineTo(W, last.y * H);
        ctx.lineTo(W, H);
        ctx.closePath();

        const surf = ctx.createLinearGradient(0, horizonY, 0, H);
        surf.addColorStop(0,   '#e8e2d2');
        surf.addColorStop(0.5, '#bcb5a7');
        surf.addColorStop(1,   '#5a5460');
        ctx.fillStyle = surf;
        ctx.fill();

        // Craters
        for (let i = 0; i < craters.length; i++) {
            const cr = craters[i];
            const cx = cr.xN * W;
            const cy = cr.yN * H;
            const r = cr.rN * Math.min(W, H);
            ctx.save();
            ctx.translate(cx, cy);
            ctx.rotate(cr.tilt);
            // Rim shadow
            ctx.fillStyle = 'rgba(60,55,65,0.35)';
            ctx.beginPath();
            ctx.ellipse(0, 0, r, r * cr.squash, 0, 0, Math.PI * 2);
            ctx.fill();
            // Highlight on far side
            ctx.fillStyle = 'rgba(255,250,235,0.18)';
            ctx.beginPath();
            ctx.ellipse(-r * 0.18, -r * 0.28, r * 0.65, r * cr.squash * 0.55, 0, 0, Math.PI * 2);
            ctx.fill();
            ctx.restore();
        }

        ctx.restore();
    }

    function drawJar(now) {
        const j = jarPosition();
        const jw = Math.min(W, H) * 0.07;
        const jh = jw * 1.25;

        ctx.save();

        // Soft warm glow around the jar
        const glow = ctx.createRadialGradient(j.x, j.y - jh * 0.3, jw * 0.2, j.x, j.y - jh * 0.3, jw * 2.4);
        glow.addColorStop(0,   'rgba(255,220,140,0.35)');
        glow.addColorStop(0.5, 'rgba(255,200,120,0.12)');
        glow.addColorStop(1,   'rgba(255,200,120,0)');
        ctx.fillStyle = glow;
        ctx.beginPath();
        ctx.arc(j.x, j.y - jh * 0.3, jw * 2.4, 0, Math.PI * 2);
        ctx.fill();

        // Jar body — rounded glass shape
        ctx.fillStyle = 'rgba(160,180,210,0.20)';
        ctx.strokeStyle = 'rgba(220,230,250,0.65)';
        ctx.lineWidth = 1.4;
        const jx = j.x - jw / 2;
        const jy = j.y - jh;
        const r = jw * 0.18;
        roundRect(ctx, jx, jy, jw, jh, r);
        ctx.fill();
        ctx.stroke();

        // Jar lid
        const lidH = jh * 0.12;
        ctx.fillStyle = 'rgba(220,200,150,0.55)';
        ctx.strokeStyle = 'rgba(180,160,110,0.75)';
        roundRect(ctx, jx - 2, jy - lidH, jw + 4, lidH * 1.3, r * 0.4);
        ctx.fill();
        ctx.stroke();

        // Tiny twinkling stars inside the jar (the "supply")
        const inside = 5;
        for (let i = 0; i < inside; i++) {
            const ang = (i / inside) * Math.PI * 2 + now * 0.0006;
            const rad = jw * 0.18 + (i % 2) * jw * 0.10;
            const sx = j.x + Math.cos(ang) * rad;
            const sy = j.y - jh * 0.45 + Math.sin(ang) * rad * 0.7;
            const tw = 0.5 + 0.5 * Math.sin(now * 0.003 + i);
            ctx.fillStyle = `rgba(255,240,180,${0.6 + 0.4 * tw})`;
            ctx.beginPath();
            ctx.arc(sx, sy, 1.4 + tw * 0.6, 0, Math.PI * 2);
            ctx.fill();
        }

        ctx.restore();
    }

    function drawPlacedStars(now) {
        for (let i = 0; i < placedStars.length; i++) {
            const s = placedStars[i];
            const age = (now - s.bornAt) / 1000;
            // First 400ms: settle-in pop (scale > 1 then settles).
            let scale = 1;
            if (age < 0.4) {
                const t = age / 0.4;
                scale = 1 + 0.7 * (1 - easeOutBack(t));
            }
            drawStar(s.x, s.y, 4.5 * scale, 1.0);
        }
    }

    function drawStar(x, y, r, alpha) {
        ctx.save();
        // Halo
        const halo = ctx.createRadialGradient(x, y, 0, x, y, r * 3.2);
        halo.addColorStop(0,   `rgba(255,250,210,${0.85 * alpha})`);
        halo.addColorStop(0.4, `rgba(255,240,170,${0.32 * alpha})`);
        halo.addColorStop(1,   'rgba(255,240,170,0)');
        ctx.fillStyle = halo;
        ctx.beginPath();
        ctx.arc(x, y, r * 3.2, 0, Math.PI * 2);
        ctx.fill();

        // Core
        ctx.fillStyle = `rgba(255,255,240,${0.98 * alpha})`;
        ctx.beginPath();
        ctx.arc(x, y, r, 0, Math.PI * 2);
        ctx.fill();

        // Cross spikes — four soft rays
        ctx.strokeStyle = `rgba(255,250,210,${0.6 * alpha})`;
        ctx.lineWidth = 0.8;
        ctx.lineCap = 'round';
        ctx.beginPath();
        ctx.moveTo(x - r * 2.6, y); ctx.lineTo(x + r * 2.6, y);
        ctx.moveTo(x, y - r * 2.6); ctx.lineTo(x, y + r * 2.6);
        ctx.stroke();

        ctx.restore();
    }

    function drawInFlight(now) {
        for (let i = inFlight.length - 1; i >= 0; i--) {
            const f = inFlight[i];
            const t = (now - f.t0) / f.dur;
            if (t >= 1) {
                // Landed — convert to placed star.
                placedStars.push({
                    x: f.to.x,
                    y: f.to.y,
                    bornAt: now,
                    indexInConstellation: f.indexInConstellation,
                });
                spawnSparkleBurst(f.to.x, f.to.y, 10, STAR_SPARKLE_COLORS);
                try { Audio.starPlace(0.8, f.indexInConstellation); } catch (_) {}
                inFlight.splice(i, 1);
                continue;
            }
            const e = ease(clamp(t, 0, 1));
            // Quadratic arc: midpoint elevated above the straight line.
            const midX = (f.from.x + f.to.x) / 2;
            const midY = Math.min(f.from.y, f.to.y) - Math.abs(f.from.x - f.to.x) * 0.20 - H * 0.10;
            // Quadratic Bezier
            const u = 1 - e;
            const x = u * u * f.from.x + 2 * u * e * midX + e * e * f.to.x;
            const y = u * u * f.from.y + 2 * u * e * midY + e * e * f.to.y;
            drawStar(x, y, 3 + e * 1.5, 0.7 + e * 0.3);

            // Trailing sparkle dots
            if (Math.random() < 0.3) {
                particles.push({
                    x, y,
                    dx: (Math.random() - 0.5) * 0.4,
                    dy: 0.4 + Math.random() * 0.3,
                    r: 0.6 + Math.random() * 0.8,
                    life: 24,
                    color: '#fff5d0',
                });
            }
        }
    }

    function drawConstellationReveal(now) {
        if (!reveal || !current) return;
        const tNorm = clamp((now - reveal.t0) / reveal.dur, 0, 1);

        // Lines phase: first 60% of reveal duration draws connecting lines.
        const linePhase = clamp(tNorm / 0.6, 0, 1);
        // Bloom phase: last 40% adds a soft pulse around each star.
        const bloomPhase = clamp((tNorm - 0.6) / 0.4, 0, 1);

        const edges = current.template.edges;
        const stars = placedStars;

        // Draw partial-progress lines.
        const totalEdges = edges.length;
        const drawnUpTo = linePhase * totalEdges;

        ctx.save();
        ctx.lineCap = 'round';
        ctx.lineJoin = 'round';

        for (let i = 0; i < totalEdges; i++) {
            const [aIdx, bIdx] = edges[i];
            const a = stars[aIdx];
            const b = stars[bIdx];
            if (!a || !b) continue;
            let frac = clamp(drawnUpTo - i, 0, 1);
            if (frac <= 0) continue;
            const x2 = a.x + (b.x - a.x) * frac;
            const y2 = a.y + (b.y - a.y) * frac;

            // Outer glow stroke
            ctx.strokeStyle = `rgba(255,230,150,${0.20 + 0.10 * bloomPhase})`;
            ctx.lineWidth = 4 + 2 * bloomPhase;
            ctx.beginPath();
            ctx.moveTo(a.x, a.y);
            ctx.lineTo(x2, y2);
            ctx.stroke();

            // Inner crisp line
            ctx.strokeStyle = `rgba(255,250,220,${0.85})`;
            ctx.lineWidth = 1.6;
            ctx.beginPath();
            ctx.moveTo(a.x, a.y);
            ctx.lineTo(x2, y2);
            ctx.stroke();
        }
        ctx.restore();

        // Bloom around each star.
        if (bloomPhase > 0) {
            for (let i = 0; i < stars.length; i++) {
                const s = stars[i];
                const pulse = Math.sin(bloomPhase * Math.PI);
                const r = 6 + pulse * 6;
                ctx.save();
                const g = ctx.createRadialGradient(s.x, s.y, 0, s.x, s.y, r * 3);
                g.addColorStop(0,   `rgba(255,240,180,${0.5 * pulse})`);
                g.addColorStop(0.5, `rgba(255,220,140,${0.18 * pulse})`);
                g.addColorStop(1,   'rgba(255,220,140,0)');
                ctx.fillStyle = g;
                ctx.beginPath();
                ctx.arc(s.x, s.y, r * 3, 0, Math.PI * 2);
                ctx.fill();
                ctx.restore();
            }
        }

        // When the reveal animation completes, transition to "completing".
        if (tNorm >= 1 && phase === 'revealing') {
            phase = 'completing';
            // Burst of sparkles along the lines
            for (let i = 0; i < edges.length; i++) {
                const [aIdx, bIdx] = edges[i];
                const a = stars[aIdx];
                const b = stars[bIdx];
                if (!a || !b) continue;
                spawnSparkleBurst((a.x + b.x) / 2, (a.y + b.y) / 2, 8, REVEAL_SPARKLE_COLORS);
            }
            try { Audio.constellationName(0.7); } catch (_) {}
            setTimeoutSafe(completeConstellation, 1100);
        }
    }

    function drawShootingStars() {
        for (let i = shootingStars.length - 1; i >= 0; i--) {
            const s = shootingStars[i];
            s.x += s.vx;
            s.y += s.vy;
            s.age++;
            if (s.age >= s.maxAge || s.x < -120 || s.x > W + 120) {
                shootingStars.splice(i, 1);
                continue;
            }

            // Trail
            ctx.save();
            const tailX = s.x - s.vx * (s.len / Math.hypot(s.vx, s.vy));
            const tailY = s.y - s.vy * (s.len / Math.hypot(s.vx, s.vy));
            const grad = ctx.createLinearGradient(tailX, tailY, s.x, s.y);
            grad.addColorStop(0, 'rgba(255,240,200,0)');
            grad.addColorStop(1, 'rgba(255,250,230,0.85)');
            ctx.strokeStyle = grad;
            ctx.lineCap = 'round';
            ctx.lineWidth = 2;
            ctx.beginPath();
            ctx.moveTo(tailX, tailY);
            ctx.lineTo(s.x, s.y);
            ctx.stroke();

            // Head
            ctx.fillStyle = 'rgba(255,250,230,0.9)';
            ctx.beginPath();
            ctx.arc(s.x, s.y, 1.6, 0, Math.PI * 2);
            ctx.fill();
            ctx.restore();
        }
    }

    function drawParticles() {
        for (let i = particles.length - 1; i >= 0; i--) {
            const p = particles[i];
            p.x += p.dx;
            p.y += p.dy;
            p.dy += 0.02; // tiny gravity
            p.life--;
            if (p.life <= 0) {
                particles.splice(i, 1);
                continue;
            }
            const a = p.life / 30;
            ctx.fillStyle = p.color;
            ctx.globalAlpha = clamp(a, 0, 1);
            ctx.beginPath();
            ctx.arc(p.x, p.y, p.r, 0, Math.PI * 2);
            ctx.fill();
            ctx.globalAlpha = 1;
        }
    }

    function drawDigitHUD(now) {
        if (!current) return;
        const d = expectedDigit();
        const isZero = d === 0;

        // Floating glass card top-center. Kept tight to the top edge so it
        // doesn't intrude into the sky region where the constellation forms.
        const cardW = Math.min(W * 0.13, 170);
        const cardH = cardW * 0.78;
        const cx = W / 2;
        const cy = H * 0.115;

        ctx.save();

        // Soft drop shadow
        ctx.fillStyle = 'rgba(0,0,0,0.25)';
        roundRect(ctx, cx - cardW / 2 + 2, cy - cardH / 2 + 6, cardW, cardH, 22);
        ctx.fill();

        // Glass background
        const grad = ctx.createLinearGradient(0, cy - cardH / 2, 0, cy + cardH / 2);
        grad.addColorStop(0, 'rgba(255,255,255,0.20)');
        grad.addColorStop(1, 'rgba(255,255,255,0.08)');
        ctx.fillStyle = grad;
        roundRect(ctx, cx - cardW / 2, cy - cardH / 2, cardW, cardH, 22);
        ctx.fill();

        ctx.strokeStyle = isZero
            ? 'rgba(255,220,140,0.95)'
            : 'rgba(255,255,255,0.6)';
        ctx.lineWidth = 1.6;
        ctx.stroke();

        // Pulse the card softly when waiting on input
        const pulse = 0.5 + 0.5 * Math.sin(now * 0.004);

        // Big digit
        const fontPx = Math.round(cardH * 0.66);
        ctx.font = `900 ${fontPx}px system-ui, -apple-system, Segoe UI, Arial, sans-serif`;
        ctx.textAlign = 'center';
        ctx.textBaseline = 'middle';

        if (isZero) {
            // Gold halo for the climax digit
            const halo = ctx.createRadialGradient(cx, cy, 0, cx, cy, cardW * 0.5);
            halo.addColorStop(0,   `rgba(255,220,140,${0.25 + 0.20 * pulse})`);
            halo.addColorStop(1,   'rgba(255,220,140,0)');
            ctx.fillStyle = halo;
            ctx.fillRect(cx - cardW / 2, cy - cardH / 2, cardW, cardH);

            ctx.fillStyle = `rgba(255,235,160,${0.95 + 0.05 * pulse})`;
        } else {
            ctx.fillStyle = `rgba(255,255,255,${0.92 + 0.06 * pulse})`;
        }

        // Outline for legibility on busy background
        ctx.strokeStyle = 'rgba(0,0,0,0.55)';
        ctx.lineWidth = Math.max(2, Math.round(fontPx * 0.07));
        ctx.lineJoin = 'round';
        ctx.miterLimit = 2;
        ctx.strokeText(String(d), cx, cy);
        ctx.fillText(String(d), cx, cy);

        // Sequence preview row beneath the card. Shows the actual random
        // sequence she'll be pressing tonight (with 0 at the end), so she can
        // glance ahead. The current digit pulses gold; placed ones fade.
        if (current.template && current.digitSequence) {
            const seq = current.digitSequence;
            const placed = current.placedCount;
            const rowY = cy + cardH / 2 + 18;
            const dotsCount = seq.length + 1; // include 0
            const spacing = Math.min(22, cardW * 1.15 / (dotsCount + 1));
            const fullWidth = (dotsCount - 1) * spacing;
            const startX = cx - fullWidth / 2;
            ctx.textAlign = 'center';
            ctx.textBaseline = 'middle';
            ctx.font = `700 ${Math.round(spacing * 0.78)}px system-ui, -apple-system, Segoe UI, Arial, sans-serif`;
            for (let i = 0; i < dotsCount; i++) {
                const digit = i < seq.length ? seq[i] : 0;
                const isFilled = i < placed;
                const isCurrent = i === placed;
                const dx = startX + i * spacing;
                if (isCurrent) {
                    ctx.fillStyle = digit === 0
                        ? 'rgba(255,220,140,1.0)'
                        : 'rgba(255,235,160,0.95)';
                } else if (isFilled) {
                    ctx.fillStyle = 'rgba(255,255,255,0.55)';
                } else {
                    ctx.fillStyle = 'rgba(255,255,255,0.30)';
                }
                ctx.fillText(String(digit), dx, rowY);
            }
        }

        ctx.restore();
    }

    // ── Main loop ─────────────────────────────────────────────────────────
    let rafId = null;

    function frameLoop() {
        if (disposed) return;
        syncSize();
        const now = nowMs();

        ctx.clearRect(0, 0, W, H);

        drawSky();
        drawBackgroundStars(now);
        drawCollectedConstellations(now);
        drawEarth(now);
        drawMoonSurface();
        drawJar(now);

        drawPlacedStars(now);
        drawInFlight(now);
        drawConstellationReveal(now);
        drawParticles();
        drawShootingStars();

        drawDigitHUD(now);

        rafId = requestAnimationFrame(frameLoop);
    }

    // ── Public API ────────────────────────────────────────────────────────
    const api = { pressDigit };

    return {
        start() {
            syncSize();
            notifyStats();
            startNextConstellation();
            rafId = requestAnimationFrame(frameLoop);
        },
        dispose() {
            disposed = true;
            if (rafId !== null) { cancelAnimationFrame(rafId); rafId = null; }
            for (const id of timers) clearTimeout(id);
            timers.clear();
            inFlight.length = 0;
            placedStars.length = 0;
            shootingStars.length = 0;
            particles.length = 0;
            current = null;
            reveal = null;
        },
        api,
    };
}
